# Generated by Django 5.2.5 on 2025-08-17 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_room_alter_roomparticipant_room_delete_create_room"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="description",
        ),
        migrations.RemoveField(
            model_name="room",
            name="host",
        ),
        migrations.RemoveField(
            model_name="room",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="room",
            name="is_private",
        ),
        migrations.RemoveField(
            model_name="room",
            name="max_participants",
        ),
        migrations.RemoveField(
            model_name="room",
            name="name",
        ),
        migrations.RemoveField(
            model_name="room",
            name="password",
        ),
        migrations.RemoveField(
            model_name="room",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="room",
            name="code",
            field=models.CharField(
                blank=True, editable=False, max_length=6, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rooms",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="members",
            field=models.ManyToManyField(
                blank=True, related_name="joined_rooms", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="room_name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name="RoomParticipant",
        ),
    ]
