# Generated by Django 5.2.5 on 2025-08-17 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_remove_room_description_remove_room_host_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="description",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
