# Generated by Django 5.2.5 on 2025-08-17 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_room_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="description",
            field=models.TextField(max_length=200, null=True),
        ),
    ]
